language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '9'
  - '8'
services:
  - mongodb
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
script:
  - yarn test
jobs:
  include:
    - stage: release
      node_js: '10'
      before_install:
        - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
      script:
        - yarn test
        - yarn build
      after_success:
        - yarn report-coverage
        - yarn semantic-release
